Add option to select fixed width progress bar
complexlogic/rsgain pull request #28
Opened 2022-10-25 09:07 UTC by diizzyy

This option makes progress bar not scale to column width and sets it to fit within 80 cols

2022-10-26 00:06 UTC, complexlogic commented
Can you explain the motivation for this change? What issue does this solve?

2022-10-26 00:45 UTC, diizzyy commented
Even if you have a window open that's wider than lets say 80 cols necessarily mean that you only want a progress bar to cover the full width as it reduces for readability (for example exhale also limits width). LAME is the only encoder I know that also uses full width

Looking at a few others,
flac (no progressbar)
twolame (no progressbar)
oggenc (no progressbar but indicator)
opusenc (no progressbar but indicator)
wavpack (no progressbar but indicator)

2022-10-26 07:31 UTC, complexlogic commented
Thanks for the context. I can see how this feature could be desirable, but I have a few suggestions:
- I don't want the progress bar to be fixed width. That means the progress bar will wrap to the next line if the console width is less than 80 characters. I think this feature would be better implemented as a *maximum* width instead.
- Perhaps instead of an ON/OFF setting, allow the user to specify the maximum. For example, `-DMAX_PROGBAR_WIDTH=80`

I might be able to use this feature on the Windows build to increase the performance of the progress bar.

2022-10-26 08:45 UTC, diizzyy commented
@complexlogic 
Something like that?

2022-10-27 14:22 UTC, complexlogic requested changes

2022-10-27 14:22 UTC, complexlogic commented on CMakeLists.txt
> +option(SCALEPROGBAR "Scale progress bar to column width" ON)
No need to have the on/off option. We can check for the existence of the width variable to determine the state of the setting

2022-10-27 14:22 UTC, complexlogic commented on CMakeLists.txt
> +set(PROGBARWIDTH "80" CACHE STRING "Fixed width of progress bar")
Should be called MAXPROGBARWIDTH to state that it is a maximum value, not fixed

2022-10-27 14:22 UTC, complexlogic commented on src/CMakeLists.txt
> +  if(SCALEPROGBAR)
Refactor this to check for the definition of the cache variable as defined as above. You will also need to add a bounds check. i.e. the value should not be negative

2022-10-27 14:22 UTC, complexlogic commented on src/output.cpp
> +#ifdef SCALEDPROGRESSBAR
Remove the condtional for the on/off. Always check for the width, then set to the max if it exceeds. Something like this:
```C++
w = this->get_console_width();
#ifdef MAXPROGBARWIDTH
if (w > MAXPROGBARWIDTH)
    w = MAXPROGBARWIDTH
#endif
w -= 8;
if (w <= 0)
    return;
```

2022-10-27 21:46 UTC, diizzyy commented
That seems like a more clean approach. Unfortunately I'll be busy until ~mid next week so feel free to refactor and commit if you want.

2022-10-28 00:53 UTC, merged